vim.keymap.set('n', '<leader>gb', ':Git branch<space>')
vim.keymap.set('n', '<leader>gcp', ':Git cherry-pick<space>')
vim.keymap.set('n', '<leader>gcw', '<cmd>Git wip<CR>')
vim.keymap.set('n', '<leader>gd', '<cmd>Gdiffsplit!<CR>')
vim.keymap.set('n', '<leader>ge', '<cmd>Gedit<CR>')
vim.keymap.set('n', '<leader>gh', '<cmd>0Gclog<CR>')
vim.keymap.set('n', '<leader>gl', ':Gclog<space>')
vim.keymap.set('n', '<leader>gm', ':GMove<space>%:h/')
vim.keymap.set('n', '<leader>go', ':Git checkout<space>')
vim.keymap.set('n', '<leader>gpf', '<cmd>Start! git fetch<CR>')
vim.keymap.set('n', '<leader>gpl', '<cmd>Start! git pull<CR>')
vim.keymap.set('n', '<leader>gpr', '<cmd>Start! git repush<CR>')
vim.keymap.set('n', '<leader>gps', '<cmd>Start! git push<CR>')
vim.keymap.set('n', '<leader>gr', '<cmd>Gread<CR>')
vim.keymap.set('n', '<leader>gs', '<cmd>0Git<CR>')
vim.keymap.set('n', '<leader>gw', '<cmd>Gwrite<CR>')
vim.keymap.set('n', '<leader>gx', '<cmd>GDelete<CR>')
vim.keymap.set('n', '<leader>g;', ':Ggrep -q<space>')
