local builtin = require('telescope.builtin')
local ht = require('haskell-tools')
require('telescope').load_extension('fzf')

vim.keymap.set('n', '<leader><space>', builtin.git_files)
vim.keymap.set('n', '<leader>,', builtin.buffers)
vim.keymap.set('n', '<leader>.', builtin.find_files)
vim.keymap.set('n', '<leader>/', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>*', builtin.grep_string)
vim.keymap.set('n', '<leader>vg', builtin.live_grep)
vim.keymap.set('n', '<leader>vd', builtin.diagnostics)
vim.keymap.set('n', '<leader>vh', builtin.help_tags)
vim.keymap.set('n', '<leader>vs', ht.hoogle.hoogle_signature)
