anchors:
  - &dell age1uvd9szwgg3zass82fhg4xyx3qm7kn6dtknnxmylyc39ykrhuupdqt4pr3g
  - &hp age15wy4pdek4mjflc9je4lp0pw96xdjp3r73f9ad6syysjh5da5pvjqrxj6cg
  - &nixos-vm age17pzf28qms6xna4pfyyflvrg9ks4w9dsfh0qs4esz3nl0jm4ds4pqwdthjs
  - &x230t age1kmhmqv39xsatvcjtkgkzy65c0e02z7g0uedknaneq5z8xz594dgqpk4gdg
  - &tjanas CAE5FB0B2554626A9A899F0E3194693FF9330274

creation_rules:
  - key_groups:
    - age:
      - *dell
      - *hp
      - *nixos-vm
      - *x230t
      pgp:
      - *tjanas
    path_regex: hosts/common/secrets.ya?ml$
  - key_groups:
    - age:
      - *dell
      pgp:
      - *tjanas
    path_regex: hosts/dell/secrets.ya?ml$
  - key_groups:
    - age:
      - *hp
      pgp:
      - *tjanas
    path_regex: hosts/hp/secrets.ya?ml$
  - key_groups:
    - age:
      - *nixos-vm
      pgp:
      - *tjanas
    path_regex: hosts/nixos-vm/secrets.ya?ml$
  - key_groups:
    - age:
      - *x230t
      pgp:
      - *tjanas
    path_regex: hosts/x230t/secrets.ya?ml$
