{
  imports = [
    ./common
    ./common/devenv/devtools.nix
    ./common/devenv/emacs.nix
    ./common/devenv/email.nix
    ./common/devenv/scripts.nix
    ./common/programs/alacritty.nix
    ./common/programs/dunst.nix
    ./common/programs/gui.nix
    ./common/programs/herbstluftwm.nix
    ./common/programs/picom.nix
    ./common/programs/polybar.nix
    ./common/programs/rofi-pass.nix
    ./common/programs/sxiv.nix
    ./common/programs/theme.nix
    ./common/programs/xsession.nix
    ./common/programs/zathura.nix
  ];
}
