#!/usr/bin/env bash

set -euo pipefail

BASEDIR=$(dirname $(dirname $(readlink -f $0)))

if [ $UID -ne 0 ]; then
    echo "must be run as root" >&2
    exit 1
fi

if [ $# -ne 2 ]; then
    echo "usage: $0 <device> <host>" >&2
    exit 1
fi

DEV=$1
HOST=$2

if [ ! -b "$DEV" ]; then
    echo "device $DEV does not exist" >&2
    exit 1
fi

if ! nix flake show "$BASEDIR" | grep -q "${HOST}.*NixOS configuration"; then
    echo "nixos configuration $HOST does not exist" >&2
    exit 1
fi

cd $(mktemp -d)

export GPG_TTY=$(tty)
export GNUPGHOME="$(pwd)/gnupg"
mkdir -p "$GNUPGHOME"
echo "pinentry-program $(command -v pinentry-curses)" > "$GNUPGHOME/gpg-agent.conf"
gpg --import "$BASEDIR/config/gnupg/public.asc"
gpg --card-status

umask 0077
gpg -d "$BASEDIR/config/gnupg/cryptkey.gpg" > crypto_keyfile.bin
dd if=/dev/zero of=crypto_header.bin bs=16M count=1
cryptsetup luksFormat --batch-mode crypto_header.bin crypto_keyfile.bin
cryptsetup luksAddKey --key-file crypto_keyfile.bin crypto_header.bin
mkpasswd -m sha-512 > password_file
umask 0022

parted "$DEV" -- mklabel gpt
parted "$DEV" -- mkpart 'bios-grub' 1MiB 2MiB
parted "$DEV" -- mkpart 'boot' 2MiB 1GiB
parted "$DEV" -- mkpart 'root' 1GiB 100%
parted "$DEV" -- set 1 bios_grub on
parted "$DEV" -- set 2 esp on
udevadm trigger

cryptsetup luksHeaderRestore --header-backup-file crypto_header.bin --batch-mode /dev/disk/by-partlabel/root
cryptsetup open --key-file crypto_keyfile.bin /dev/disk/by-partlabel/root luks-root

mkfs.btrfs -L 'nixos-system' /dev/mapper/luks-root
mount /dev/mapper/luks-root /mnt
btrfs subvolume create /mnt/root
btrfs subvolume create /mnt/home
btrfs subvolume create /mnt/nix
btrfs subvolume create /mnt/persist
btrfs subvolume create /mnt/log
btrfs subvolume create /mnt/swap
chattr +C /mnt/swap
btrfs subvolume snapshot -r /mnt/root /mnt/root-blank
umount /mnt

mount -o subvol=root,compress=zstd,noatime /dev/mapper/luks-root /mnt
mkdir -p /mnt/{boot,home,nix,persist,var/log,swap}
mount -o subvol=home,compress=zstd /dev/mapper/luks-root /mnt/home
mount -o subvol=nix,compress=zstd,noatime /dev/mapper/luks-root /mnt/nix
mount -o subvol=persist,compress=zstd,noatime /dev/mapper/luks-root /mnt/persist
mount -o subvol=log,compress=zstd,noatime /dev/mapper/luks-root /mnt/var/log
mount -o subvol=swap,noatime /dev/mapper/luks-root /mnt/swap
mv -t /mnt/persist password_file

mkfs.vfat -n boot /dev/disk/by-partlabel/boot
mount -o noatime /dev/disk/by-partlabel/boot /mnt/boot

nixos-install --no-root-password --flake "$BASEDIR#$HOST"
